### ISSUE TITLE
Minecraft Comes Alive Mod

### ISSUE THREAD

**Issue by WilliamValerian** [Fararise/Possessed#6]
When using this mod and Minecraft Comes Alive and trying to possess into a human villager sometimes crashes the game.

---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 10/10/16 1:05 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
    at mca.client.gui.GuiInteraction.<init>(GuiInteraction.java:99)
    at mca.packets.PacketOpenGUIOnEntity.processOnGameThread(PacketOpenGUIOnEntity.java:73)
    at radixcore.network.AbstractPacketHandler.processPackets(AbstractPacketHandler.java:161)
    at mca.core.forge.EventHooksFML.clientTickEventHandler(EventHooksFML.java:135)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_23_EventHooksFML_clientTickEventHandler_ClientTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:339)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1650)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Client thread
Stacktrace:
    at mca.client.gui.GuiInteraction.<init>(GuiInteraction.java:99)
    at mca.packets.PacketOpenGUIOnEntity.processOnGameThread(PacketOpenGUIOnEntity.java:73)
    at radixcore.network.AbstractPacketHandler.processPackets(AbstractPacketHandler.java:161)
    at mca.core.forge.EventHooksFML.clientTickEventHandler(EventHooksFML.java:135)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_23_EventHooksFML_clientTickEventHandler_ClientTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:339)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['William'/17248, l='MpServer', x=-638.82, y=64.00, z=-965.82]]
    Chunk stats: MultiplayerChunkCache: 271, 271
    Level seed: 0
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-535,4,-836), Chunk: (at 9,0,12 in -34,-53; contains blocks -544,0,-848 to -529,255,-833), Region: (-2,-2; contains chunks -64,-64 to -33,-33, blocks -1024,0,-1024 to -513,255,-513)
    Level time: 9764 game time, 5936 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 70 total; [EntityHuman['Suzan'/194305, l='MpServer', x=-628.30, y=67.00, z=-948.70], EntityWolf['Destroyers'/161046, l='MpServer', x=-629.89, y=64.00, z=-958.14], EntityItem['item.item.ingotIron'/231707, l='MpServer', x=-643.57, y=65.00, z=-937.29], EntityItem['item.tile.flower2.poppy'/231706, l='MpServer', x=-643.32, y=65.00, z=-935.80], EntityWolf['Destroyers'/161304, l='MpServer', x=-634.30, y=64.00, z=-962.30], EntityCreeper['Creeper'/416540, l='MpServer', x=-655.50, y=65.00, z=-1001.50], EntityWolf['Destroyers'/163111, l='MpServer', x=-629.14, y=64.00, z=-959.75], EntityItem['item.item.seeds'/227621, l='MpServer', x=-619.88, y=64.00, z=-950.27], EntityHuman['Jasper'/242991, l='MpServer', x=-647.50, y=64.00, z=-945.22], EntityWolf['Destroyers'/159797, l='MpServer', x=-628.70, y=64.00, z=-957.46], EntityHuman['Sylvia'/95803, l='MpServer', x=-639.29, y=64.00, z=-929.46], EntityWolf['Destroyers'/147518, l='MpServer', x=-633.52, y=64.00, z=-961.85], EntityWolf['Destroyers'/145980, l='MpServer', x=-629.98, y=64.00, z=-959.65], EntityHuman['Nani'/70209, l='MpServer', x=-666.26, y=64.00, z=-968.62], EntityHuman['Jeffery'/70210, l='MpServer', x=-628.21, y=64.00, z=-966.35], EntityWolf['Destroyers'/148554, l='MpServer', x=-632.52, y=64.00, z=-960.45], EntityItem['item.item.wheat'/420942, l='MpServer', x=-636.36, y=64.00, z=-963.67], EntityItem['item.item.beetroot_seeds'/420940, l='MpServer', x=-636.36, y=64.00, z=-963.67], EntityItem['item.item.seeds'/420941, l='MpServer', x=-636.36, y=64.00, z=-963.67], EntityWolf['Destroyers'/166734, l='MpServer', x=-629.33, y=64.00, z=-960.74], EntityItem['item.item.seeds'/259919, l='MpServer', x=-657.67, y=64.00, z=-930.61], EntityItem['item.item.carrots'/420938, l='MpServer', x=-636.36, y=64.00, z=-963.67], EntityItem['item.item.beetroot'/420939, l='MpServer', x=-636.36, y=64.00, z=-963.67], EntityItem['item.item.potato'/420937, l='MpServer', x=-636.36, y=64.00, z=-963.67], EntityItem['item.item.seeds'/210777, l='MpServer', x=-621.12, y=64.00, z=-944.51], EntityZombie['Zombie'/413030, l='MpServer', x=-666.21, y=65.00, z=-990.50], EntityPlayerSP['William'/17248, l='MpServer', x=-638.82, y=64.00, z=-965.82], EntityZombie['Zombie'/413029, l='MpServer', x=-656.57, y=65.00, z=-991.18], EntitySpider['Spider'/413026, l='MpServer', x=-658.90, y=65.00, z=-990.08], EntityItem['item.item.beetroot_seeds'/395887, l='MpServer', x=-611.52, y=64.00, z=-947.24], EntitySquid['Squid'/345199, l='MpServer', x=-651.94, y=60.80, z=-939.02], EntitySquid['Squid'/345200, l='MpServer', x=-651.40, y=56.22, z=-939.73], EntityCreeper['Creeper'/374652, l='MpServer', x=-666.27, y=65.00, z=-991.99], EntityHuman['Francis'/292729, l='MpServer', x=-638.63, y=65.00, z=-935.87], EntityHuman['Eusebio'/145023, l='MpServer', x=-604.50, y=64.00, z=-958.68], EntityItem['item.item.seeds'/224381, l='MpServer', x=-618.19, y=64.00, z=-950.75], EntityWolf['Destroyers'/155014, l='MpServer', x=-630.77, y=64.00, z=-959.50], EntityWolf['Destroyers'/163461, l='MpServer', x=-631.09, y=64.00, z=-960.57], EntityWolf['Destroyers'/153755, l='MpServer', x=-630.27, y=64.00, z=-957.34], EntityItem['item.item.beetroot_seeds'/396441, l='MpServer', x=-609.95, y=64.00, z=-947.72], EntityItem['item.item.seeds'/210853, l='MpServer', x=-623.65, y=64.00, z=-944.76], EntityCreeper['Creeper'/380588, l='MpServer', x=-656.50, y=65.00, z=-1005.50], EntityWolf['Destroyers'/146351, l='MpServer', x=-628.13, y=64.00, z=-959.12], EntityWolf['Destroyers'/148911, l='MpServer', x=-632.07, y=64.00, z=-961.20], EntitySquid['Squid'/168372, l='MpServer', x=-650.40, y=56.32, z=-938.45], EntityWolf['Destroyers'/145343, l='MpServer', x=-630.63, y=64.00, z=-958.02], EntityIronGolem['Jessica'/80322, l='MpServer', x=-636.36, y=64.00, z=-963.67], EntityBat['Bat'/222670, l='MpServer', x=-660.30, y=53.98, z=-996.25], EntityHuman['Leonel'/19407, l='MpServer', x=-596.50, y=64.00, z=-965.76], EntityHuman['Kareem'/17627, l='MpServer', x=-663.27, y=64.00, z=-943.76], EntityHuman['Josef'/17628, l='MpServer', x=-677.21, y=65.00, z=-935.31], EntityHuman['Leif'/17629, l='MpServer', x=-640.74, y=65.00, z=-920.52], EntityHuman['Ezekiel'/17631, l='MpServer', x=-651.50, y=65.00, z=-941.73], EntityWolf['Destroyers'/146658, l='MpServer', x=-627.76, y=64.00, z=-960.07], EntityHuman['Jannette'/17632, l='MpServer', x=-644.49, y=64.00, z=-949.70], EntityWolf['Destroyers'/159456, l='MpServer', x=-631.07, y=64.00, z=-958.84], EntityHuman['Dorian'/17635, l='MpServer', x=-625.51, y=64.00, z=-936.70], EntityHuman['Ezequiel'/17636, l='MpServer', x=-638.49, y=65.00, z=-950.26], EntityHuman['Maragret'/17637, l='MpServer', x=-639.21, y=65.00, z=-948.85], EntityHuman['Thomas'/169447, l='MpServer', x=-630.70, y=67.00, z=-948.70], EntityHuman['Augustus'/17640, l='MpServer', x=-639.25, y=64.00, z=-940.51], EntityHuman['Miles'/17642, l='MpServer', x=-638.22, y=65.00, z=-942.52], EntityHuman['Evie'/17644, l='MpServer', x=-649.52, y=65.00, z=-936.26], EntityHuman['Magnolia'/17645, l='MpServer', x=-641.25, y=65.00, z=-948.47], EntityHuman['Nichol'/17646, l='MpServer', x=-617.30, y=65.00, z=-969.30], EntityHuman['Broderick'/17647, l='MpServer', x=-630.70, y=65.00, z=-942.30], EntityHuman['Kareem'/17648, l='MpServer', x=-637.33, y=64.01, z=-933.92], EntityHuman['Roni'/17651, l='MpServer', x=-636.58, y=64.00, z=-966.74], EntityHuman['Coleen'/17653, l='MpServer', x=-611.52, y=65.00, z=-954.70], EntityHuman['Bibi'/17654, l='MpServer', x=-591.76, y=65.00, z=-959.51]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Windows 7 (x86) version 6.1
    Java Version: 1.8.0_101, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    Memory: 49396880 bytes (47 MB) / 523501568 bytes (499 MB) up to 523501568 bytes (499 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
    FML: MCP 9.32 Powered by Forge 12.18.1.2094 8 mods loaded, 8 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAAAAAAA  mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAAAAAAA  FML{8.0.99.99} [Forge Mod Loader](forge-1.10.2-12.18.1.2094.jar) 
    UCHIJAAAAAAAAA  Forge{12.18.1.2094} [Minecraft Forge](forge-1.10.2-12.18.1.2094.jar) 
    UCHIJAAAAAAAAA  Bullseye{1.0.2} [Bullseye](Bullseye-Mod-1.10.2.jar) 
    UCHIJAAAAAAAAA  am{1.5.5} [Marines Armor and Weapons](Marines Armor and Weapons 1.5.7.jar) 
    UCHIJAAAAAAAAA  RadixCore{1.10.2-2.1.2} [RadixCore](RadixCore-1.10.2-2.1.2-universal.jar) 
    UCHIJAAAAAAAAA  MCA{1.10.2-5.2.1} [Minecraft Comes Alive](MCA-1.10.2-5.2.1-universal.jar) 
    UCHIJAAAAAAAAA  possessed{1.0.0} [Possessed](possessed-1.0.0.jar) 
    Loaded coremods (and transformers): 
    GL info: ' Vendor: 'Intel' Version: '4.2.0 - Build 10.18.10.3345' Renderer: 'Intel(R) HD Graphics 4400'
    Launched Version: 1.10.2-forge1.10.2-12.18.1.2094
    LWJGL: 2.9.4
    OpenGL: Intel(R) HD Graphics 4400 GL version 4.2.0 - Build 10.18.10.3345, Intel
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: Permanent Steve.zip
Current Language: English (United Kingdom)
Profiler Position: N/A (disabled)
CPU: 4x Intel(R) Core(TM) i3-4150 CPU @ 3.50GHz
```

**Comment by Fararise** [comment]
Unfortunately it doesn't look like there is much I can do about this. I'll look into a bit more though.
